### ISSUE TITLE
Returns not always current min/max

### ISSUE THREAD

**Issue by xanonid** [spebern/moving_min_max#1]
The currently returned min/max is not the min/max of all elements _currently_ in the queue, but something else.

I would expect following behaviour (different min after pre-last pop):

```rust
moving_min.push(2); 
moving_min.push(1); 
moving_min.push(3); 
assert_eq!(moving_min.min(), Some(&1));
assert_eq!(moving_min.pop(), Some(2));
assert_eq!(moving_min.min(), Some(&1));
assert_eq!(moving_min.pop(), Some(1));
assert_eq!(moving_min.min(), Some(&3));
assert_eq!(moving_min.pop(), Some(3));
assert_eq!(moving_min.min(), None);
assert_eq!(moving_min.pop(), None);
```

The recalculation of min/max on moving to the second stack seems not be 100% correct.

**Comment by spebern** [comment]
Thanks for reporting!
